# Application
spring.application.name=RevWorkforce
server.port=8082

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=hrm
spring.datasource.password=hrm123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT Configuration
app.jwt.secret=RevWorkforce_Super_Secret_Key_2024_Must_Be_At_Least_256_Bits_Long
app.jwt.expiration-ms=86400000

# Logging
logging.level.com.rev.app=DEBUG
logging.level.org.springframework.security=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false
